const ACTION_TYPES = {
  GET_MESSAGES_ACTION: 'GET_MESSAGES_ACTION',
  GET_MESSAGES_REQUEST: 'GET_MESSAGES_REQUEST',
  GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
  GET_MESSAGES_FAIL: 'GET_MESSAGES_FAIL',

  NEW_MESSAGE_ACTION: ' NEW_MESSAGE_ACTION',
  NEW_MESSAGE_SUCCESS: 'NEW_MESSAGE_SUCCESS',
  NEW_MESSAGE_FAIL: 'NEW_MESSAGE_FAIL'
};

export default ACTION_TYPES;
